<?php
// public/proof_verification.php
session_start();
require_once __DIR__ . '/../src/db.php';
require_once __DIR__ . '/../src/loan.php';
require_once __DIR__ . '/../src/upload.php';

$pdo = getPDO();
if (!isset($_SESSION['user_id']) || ($_SESSION['role'] ?? '') !== 'agent') {
    header('Location: login.php');
    exit;
}

$agent_id = $_SESSION['user_id'];
$username = $_SESSION['name'] ?? 'Agent';

// Fetch single loan application details for display or export
$selected_app_id = isset($_GET['app_id']) ? (int)$_GET['app_id'] : null;
$selected_app = null;

if ($selected_app_id) {
    $stmt = $pdo->prepare("
        SELECT la.*, u.name AS farmer_name, u.id AS farmer_user_id
        FROM loan_applications la
        INNER JOIN users u ON la.farmer_id = u.id
        WHERE la.agent_id = ? AND la.id = ?
    ");
    $stmt->execute([$agent_id, $selected_app_id]);
    $selected_app = $stmt->fetch(PDO::FETCH_ASSOC);
}

/* ==========================================
   PDF EXPORT GENERATION ROUTE
   ========================================== */
if (isset($_GET['export']) && $_GET['export'] === 'pdf' && $selected_app) {
    // Fetch all stages and their corresponding proofs for the export view
    $s_sql = "SELECT * FROM loan_stages WHERE application_id = ? ORDER BY stage_number ASC";
    $st = $pdo->prepare($s_sql);
    $st->execute([$selected_app['id']]);
    $stages = $st->fetchAll(PDO::FETCH_ASSOC);
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Loan Progress Report - #<?= $selected_app['id'] ?></title>
        <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.5; padding: 30px; }
            .header-container { border-bottom: 2px solid #0f172a; padding-bottom: 15px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
            .brand-title { font-size: 24px; font-weight: 700; color: #0f172a; margin: 0; }
            .meta-info { margin-bottom: 30px; }
            .meta-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            .meta-table td { padding: 8px 12px; border: 1px solid #e2e8f0; font-size: 14px; }
            .meta-table td.label { font-weight: 600; background-color: #f8fafc; width: 25%; }
            .section-title { font-size: 18px; font-weight: 600; color: #1e3a8a; border-bottom: 1px solid #cbd5e1; padding-bottom: 6px; margin-top: 40px; margin-bottom: 15px; }
            .stage-block { margin-bottom: 25px; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; background-color: #fafbfd; }
            .stage-header { display: flex; justify-content: space-between; font-weight: 600; font-size: 15px; margin-bottom: 15px; border-bottom: 1px dashed #cbd5e1; padding-bottom: 8px; }
            .proof-table { width: 100%; border-collapse: collapse; font-size: 13px; }
            .proof-table th, .proof-table td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
            .proof-table th { background-color: #f1f5f9; font-weight: 600; }
            .badge { padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; text-transform: uppercase; display: inline-block; }
            .badge-approved { background-color: #d1fae5; color: #065f46; }
            .badge-pending { background-color: #fef3c7; color: #92400e; }
            .badge-rejected { background-color: #fee2e2; color: #991b1b; }
            .no-print-btn { background-color: #1e40af; color: white; border: none; padding: 10px 20px; border-radius: 6px; cursor: pointer; font-size: 14px; font-weight: 600; margin-bottom: 20px; }
            @media print {
                .no-print { display: none !important; }
                body { padding: 0; }
            }
        </style>
    </head>
    <body>
        <div class="no-print" style="text-align: right;">
            <button class="no-print-btn" onclick="window.print()">Print / Export as PDF</button>
        </div>

        <div class="header-container">
            <div>
                <h1 class="brand-title">AGROLOAN PROGRESS REPORT</h1>
                <p style="margin: 5px 0 0 0; color: #64748b; font-size: 14px;">System Audit & Verification Documentation</p>
            </div>
            <div style="text-align: right; font-size: 12px; color: #64748b;">
                Export Date: <?= date('Y-m-d H:i') ?><br>
                Generated by: <?= htmlspecialchars($username) ?>
            </div>
        </div>

        <div class="meta-info">
            <h2 style="font-size: 16px; margin: 0 0 10px 0;">Application Overview</h2>
            <table class="meta-table">
                <tr>
                    <td class="label">Loan Title</td>
                    <td><?= htmlspecialchars($selected_app['title']) ?></td>
                    <td class="label">Application ID</td>
                    <td>#<?= $selected_app['id'] ?></td>
                </tr>
                <tr>
                    <td class="label">Farmer Name</td>
                    <td><?= htmlspecialchars($selected_app['farmer_name']) ?></td>
                    <td class="label">Total Stage Cost</td>
                    <td>GHS <?= number_format($selected_app['amount'], 2) ?></td>
                </tr>
                <tr>
                    <td class="label">Status</td>
                    <td><span class="badge badge-<?= ($selected_app['status'] === 'completed') ? 'approved' : 'pending' ?>"><?= htmlspecialchars($selected_app['status']) ?></span></td>
                    <td class="label">Total Disbursed</td>
                    <td>GHS <?= number_format($selected_app['disbursed_amount'], 2) ?></td>
                </tr>
            </table>
        </div>

        <div class="section-title">Timeline & Stage Verification Tracking</div>
        <?php foreach ($stages as $stage): ?>
            <div class="stage-block">
                <div class="stage-header">
                    <span>Stage <?= htmlspecialchars($stage['stage_number']) ?> (GHS <?= number_format($stage['required_amount'], 2) ?>)</span>
                    <span style="font-size: 13px; color: #475569;">Stage Status: <?= strtoupper(htmlspecialchars($stage['status'])) ?></span>
                </div>

                <?php
                $p_stmt = $pdo->prepare("SELECT * FROM stage_proofs WHERE stage_id = ? ORDER BY id ASC");
                $p_stmt->execute([$stage['id']]);
                $proofs = $p_stmt->fetchAll(PDO::FETCH_ASSOC);
                ?>

                <?php if (empty($proofs)): ?>
                    <p style="font-size: 13px; color: #64748b; margin: 0; font-style: italic;">No uploaded files present for this stage.</p>
                <?php else: ?>
                    <table class="proof-table">
                        <thead>
                            <tr>
                                <th>Proof Category</th>
                                <th>Filename</th>
                                <th>File Classification</th>
                                <th>Approval Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($proofs as $proof): ?>
                                <tr>
                                    <td>
                                        <strong>
                                            <?php 
                                            if ($proof['proof_type'] === 'before') echo 'Phase 1: Before Work';
                                            elseif ($proof['proof_type'] === 'after') echo 'Phase 2: After Work';
                                            else echo 'Phase 3: Payment Proof';
                                            ?>
                                        </strong>
                                    </td>
                                    <td><?= htmlspecialchars($proof['filename'] ?? $proof['file_path'] ?? 'N/A') ?></td>
                                    <td><?= htmlspecialchars($proof['file_type']) ?></td>
                                    <td>
                                        <span class="badge badge-<?= (strtolower($proof['status']) === 'approved') ? 'approved' : ((strtolower($proof['status']) === 'pending') ? 'pending' : 'rejected') ?>">
                                            <?= htmlspecialchars($proof['status']) ?>
                                        </span>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>

        <script>
            window.addEventListener('load', function() {
                // Pre-emptively trigger printer dialogue box
                window.print();
            });
        </script>
    </body>
    </html>
    <?php
    exit;
}

// HANDLE PROOF VERIFICATION ACTIONS
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['proof_id'], $_POST['action'])) {
    $proof_id = (int)$_POST['proof_id'];
    $action_input = $_POST['action']; 

    $new_proof_status = ($action_input === 'approve') ? 'Approved' : 'Rejected';

    try {
        $pdo->beginTransaction();

        // 1. Fetch details about the target proof and stage
        $infoStmt = $pdo->prepare("
            SELECT sp.proof_type, sp.stage_id, ls.application_id, ls.required_amount, ls.disbursed, ls.stage_number
            FROM stage_proofs sp
            JOIN loan_stages ls ON sp.stage_id = ls.id
            WHERE sp.id = ?
        ");
        $infoStmt->execute([$proof_id]);
        $info = $infoStmt->fetch(PDO::FETCH_ASSOC);

        if (!$info) {
            throw new Exception("Proof record not found.");
        }

        // 2. Update the Proof Status
        $stmt = $pdo->prepare("UPDATE stage_proofs SET status = ? WHERE id = ?");
        $stmt->execute([$new_proof_status, $proof_id]);

        // 3. Perform Stage updates depending on Action & Phase Type
        if ($new_proof_status === 'Approved') {
            
            if ($info['proof_type'] === 'before') {
                /* AUTOMATIC DISBURSEMENT ON PHASE 1 APPROVAL */
                $updateStage = $pdo->prepare("UPDATE loan_stages SET status = 'disbursed', disbursed = 1 WHERE id = ?");
                $updateStage->execute([$info['stage_id']]);

                $updateApp = $pdo->prepare("
                    UPDATE loan_applications 
                    SET disbursed_amount = disbursed_amount + ? 
                    WHERE id = ?
                ");
                $updateApp->execute([$info['required_amount'], $info['application_id']]);

                // Record audit log within disbursements table if it exists
                try {
                    $dstmt = $pdo->prepare("
                        INSERT INTO disbursements (stage_id, approved_by, status, date_approved) 
                        VALUES (?, ?, 'disbursed', NOW())
                    ");
                    $dstmt->execute([$info['stage_id'], $agent_id]);
                } catch (Exception $dex) {
                    // Fail gracefully if disbursements tracking module is not active
                }

                $_SESSION['flash_success'] = 'Phase 1 (Before Work) approved. Funds have been automatically disbursed.';

            } elseif ($info['proof_type'] === 'after' || $info['proof_type'] === 'payment') {
                /* STAGE COMPLETION REQUIREMENT CHECK */
                // Fetch all proofs for this stage to check if BOTH phase 2 (after) and phase 3 (payment) are approved
                $checkProofs = $pdo->prepare("SELECT proof_type, status FROM stage_proofs WHERE stage_id = ?");
                $checkProofs->execute([$info['stage_id']]);
                $stageProofs = $checkProofs->fetchAll(PDO::FETCH_ASSOC);

                $afterApproved = false;
                $paymentApproved = false;

                foreach ($stageProofs as $sp) {
                    $status_lower = strtolower($sp['status']);
                    if ($sp['proof_type'] === 'after' && $status_lower === 'approved') {
                        $afterApproved = true;
                    }
                    if ($sp['proof_type'] === 'payment' && $status_lower === 'approved') {
                        $paymentApproved = true;
                    }
                }

                if ($afterApproved && $paymentApproved) {
                    // Both required phases are approved -> Complete stage
                    $updateStage = $pdo->prepare("UPDATE loan_stages SET status = 'completed' WHERE id = ?");
                    $updateStage->execute([$info['stage_id']]);

                    // Shift application to next stage index
                    $updateApp = $pdo->prepare("
                        UPDATE loan_applications 
                        SET current_stage = current_stage + 1 
                        WHERE id = ?
                    ");
                    $updateApp->execute([$info['application_id']]);

                    // Verify if any remaining stages exist
                    $checkRemaining = $pdo->prepare("
                        SELECT COUNT(*) 
                        FROM loan_stages 
                        WHERE application_id = ? AND status != 'completed'
                    ");
                    $checkRemaining->execute([$info['application_id']]);
                    $remaining = $checkRemaining->fetchColumn();

                    if ($remaining == 0) {
                        $compApp = $pdo->prepare("UPDATE loan_applications SET status = 'completed' WHERE id = ?");
                        $compApp->execute([$info['application_id']]);
                        $_SESSION['flash_success'] = 'All requirements satisfied. This loan is now marked as complete.';
                    } else {
                        $_SESSION['flash_success'] = 'Phase 2 & Phase 3 are fully verified. Stage completed. Next stage unlocked.';
                    }
                } else {
                    $pendingPhaseName = (!$afterApproved) ? 'Phase 2 (After Work)' : 'Phase 3 (Payment Proof)';
                    $_SESSION['flash_success'] = ucfirst($info['proof_type']) . ' proof verified. Awaiting verification of ' . $pendingPhaseName . ' before stage transition.';
                }
            }
        } else {
            // Rejection routing
            $fallbackStatus = 'rejected_' . $info['proof_type'];
            $updateStage = $pdo->prepare("UPDATE loan_stages SET status = ? WHERE id = ?");
            $updateStage->execute([$fallbackStatus, $info['stage_id']]);
            $_SESSION['flash_success'] = 'Proof rejected. The applicant has been notified.';
        }

        $pdo->commit();

    } catch (Exception $e) {
        if ($pdo->inTransaction()) {
            $pdo->rollBack();
        }
        $_SESSION['flash_error'] = 'Update failed: ' . $e->getMessage();
    }

    $redirectUrl = "proof_verification.php" . ($selected_app_id ? "?app_id=" . $selected_app_id : "");
    header("Location: " . $redirectUrl);
    exit;
}

/* Flash messages loading */
$successMessage = $_SESSION['flash_success'] ?? '';
$errorMessage = $_SESSION['flash_error'] ?? '';
unset($_SESSION['flash_success'], $_SESSION['flash_error']);

// Fetch active portfolio allocations for this agent
$stmtList = $pdo->prepare("
    SELECT la.*, u.name AS farmer_name, u.id AS farmer_user_id,
           (SELECT COUNT(*) 
            FROM stage_proofs sp 
            JOIN loan_stages ls ON sp.stage_id = ls.id 
            WHERE ls.application_id = la.id AND sp.status = 'Pending'
           ) AS pending_count
    FROM loan_applications la
    INNER JOIN users u ON la.farmer_id = u.id
    WHERE la.agent_id = ?
    ORDER BY pending_count DESC, la.id DESC
");
$stmtList->execute([$agent_id]);
$all_applications = $stmtList->fetchAll(PDO::FETCH_ASSOC);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proof Verification</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
    <script src="https://unpkg.com/feather-icons"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <style>
    :root {
        --primary: #1e40af;      
        --primary-dark: #172554; 
        --secondary: #3b82f6; 
        
        --bg-body: #f3f4f6;
        --bg-card: #ffffff;
        --text-main: #1f2937;
        --text-muted: #6b7280;
        --danger: #ef4444;
        --warning: #f59e0b;
        --success: #10b981;
        
        --sidebar-width: 260px;
        --sidebar-collapsed: 80px;
        --shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    }

    * { box-sizing: border-box; }

    body {
        margin: 0;
        font-family: 'Poppins', sans-serif;
        background: var(--bg-body);
        color: var(--text-main);
        display: flex;
        height: 100vh;
        overflow: hidden;
    }

    .sidebar {
        width: var(--sidebar-width);
        background: var(--primary-dark);
        color: #fff;
        display: flex;
        flex-direction: column;
        padding: 20px;
        transition: width 0.3s ease;
        z-index: 100;
        box-shadow: 4px 0 10px rgba(0,0,0,0.1);
        flex-shrink: 0;
    }

    .sidebar.collapsed { width: var(--sidebar-collapsed); padding: 20px 10px; }

    .brand {
        display: flex;
        align-items: center;
        gap: 12px;
        margin-bottom: 40px;
        padding-left: 5px;
        overflow: hidden;
    }

    .brand img {
        width: 40px; height: 40px; border-radius: 8px;
        object-fit: cover; border: 2px solid rgba(255,255,255,0.2);
    }

    .brand h2 {
        font-size: 20px; font-weight: 600; white-space: nowrap;
        opacity: 1; transition: opacity 0.2s; margin: 0;
    }

    .sidebar.collapsed .brand h2 { opacity: 0; width: 0; }
    
    .nav { display: flex; flex-direction: column; gap: 8px; flex: 1; }

    .nav-link {
        display: flex; align-items: center; gap: 14px;
        padding: 12px 15px; color: #dbeafe;
        text-decoration: none; border-radius: 10px;
        transition: all 0.2s ease; white-space: nowrap; font-weight: 500;
    }

    .nav-link:hover {
        background: rgba(255,255,255,0.1); color: #fff;
        transform: translateX(4px);
    }

    .nav-link.active {
        background: var(--secondary); color: #fff;
        box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
    }

    .nav-link svg { width: 20px; height: 20px; }

    .sidebar.collapsed .nav-link { justify-content: center; padding: 12px; }
    .sidebar.collapsed .nav-link span { display: none; }
    .sidebar.collapsed .nav-link:hover { transform: none; }

    .logout-btn {
        background: rgba(239, 68, 68, 0.1); color: #fca5a5;
        border: 1px solid rgba(239, 68, 68, 0.2);
        padding: 12px; border-radius: 10px; cursor: pointer;
        display: flex; align-items: center; justify-content: center;
        gap: 10px; font-family: inherit; font-weight: 600;
        transition: 0.2s; width: 100%;
    }

    .logout-btn:hover { background: var(--danger); color: white; }
    .sidebar.collapsed .logout-btn span { display: none; }

    .main {
        flex: 1; display: flex; flex-direction: column;
        overflow-y: auto; position: relative;
        width: 100%;
    }

    .topbar {
        background: var(--bg-card); padding: 15px 30px;
        display: flex; justify-content: space-between; align-items: center;
        box-shadow: var(--shadow); position: sticky; top: 0; z-index: 50;
    }

    .toggle-btn {
        background: transparent; border: none; color: var(--text-muted);
        cursor: pointer; padding: 5px;
    }
    .toggle-btn:hover { color: var(--primary); }

    .user-profile { display: flex; align-items: center; gap: 10px; }
    .user-avatar {
        width: 35px; height: 35px; background: var(--primary);
        color: white; border-radius: 50%; display: flex;
        align-items: center; justify-content: center;
        font-weight: bold; font-size: 14px;
    }

    .content-container { padding: 30px; }
    
    .proof-card {
        background: white;
        padding: 20px;
        margin-bottom: 20px;
        border-radius: 16px;
        box-shadow: var(--shadow);
        border: 1px solid #e5e7eb;
    }

    .stage-row {
        margin-top: 25px;
        padding: 15px;
        border-radius: 12px;
        background: #f8fafc;
        border: 1px solid #e2e8f0;
    }

    .proof-grid {
        display: grid; 
        grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); 
        gap: 15px; 
        margin-top: 15px;
    }

    .proof-item {
        border: 1px solid #e5e7eb; 
        padding: 15px; 
        border-radius: 12px; 
        text-align: center;
        background: #fff;
        position: relative;
        transition: all 0.2s;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        min-height: 220px;
    }
    
    .proof-item.pending {
        border-color: var(--secondary);
        box-shadow: 0 4px 6px -1px rgba(59, 130, 246, 0.1);
    }

    .proof-item.processed {
        background: #f9fafb;
        border-color: #f3f4f6;
        opacity: 0.9;
    }

    .proof-item:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }

    .phase-badge {
        font-size: 11px;
        font-weight: 700;
        text-transform: uppercase;
        padding: 4px 8px;
        border-radius: 6px;
        margin-bottom: 8px;
        display: inline-block;
    }
    .phase-before { background-color: #fef3c7; color: #92400e; }
    .phase-after { background-color: #d1fae5; color: #065f46; }
    .phase-payment { background-color: #e0f2fe; color: #0369a1; }

    .proof-preview {
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 10px 0;
        margin-bottom: 10px;
    }
    
    .proof-preview a {
        display: flex; 
        align-items: center; 
        gap: 8px; 
        color: var(--primary); 
        text-decoration: none; 
        font-weight: 500;
        padding: 8px 16px;
        background: #eff6ff;
        border-radius: 8px;
        transition: 0.2s;
        font-size: 13px;
    }
    .proof-preview a:hover { background: #dbeafe; }

    .proof-actions {
        display: flex;
        justify-content: center;
        gap: 10px;
        margin-top: auto;
        padding-top: 10px;
    }

    .action-btn {
        border: none;
        padding: 8px 16px;
        border-radius: 6px;
        cursor: pointer;
        font-size: 13px;
        font-weight: 500;
        color: white;
        transition: background 0.2s;
        flex: 1;
    }
    
    .btn-verify { background: var(--success); }
    .btn-verify:hover { background: #059669; }
    
    .btn-reject { background: var(--danger); }
    .btn-reject:hover { background: #dc2626; }

    .proof-badge {
        display: inline-block;
        padding: 6px 12px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: 600;
        width: 100%;
    }
    .badge-verified { background: #d1fae5; color: #065f46; border: 1px solid #a7f3d0; }
    .badge-rejected { background: #fee2e2; color: #991b1b; border: 1px solid #fecaca; }

    .history-section {
        margin-top: 25px;
        border-top: 1px solid #e5e7eb;
        padding-top: 15px;
    }

    details summary {
        cursor: pointer;
        font-weight: 600;
        color: var(--text-muted);
        list-style: none; 
        display: flex;
        align-items: center;
        gap: 5px;
        padding: 10px;
        background: #f8fafc;
        border-radius: 8px;
        transition: background 0.2s;
    }
    
    details summary:hover { background: #e2e8f0; color: var(--text-main); }
    details summary::after { content: '+'; margin-left: auto; font-weight: bold; font-size: 18px; }
    details[open] summary::after { content: '-'; }

    .history-table { width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 13px; }
    .history-table th, .history-table td { text-align: left; padding: 10px; border-bottom: 1px solid #f3f4f6; }
    .history-table th { color: var(--text-muted); font-weight: 500; }

    .status-badge { padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; text-transform: capitalize; }
    .st-verified { background: #d1fae5; color: #065f46; }
    .st-rejected { background: #fee2e2; color: #991b1b; }

    /* Custom Loan Management CSS */
    .loan-table-card {
        background: #ffffff;
        border-radius: 16px;
        border: 1px solid #e5e7eb;
        box-shadow: var(--shadow);
        overflow: hidden;
    }
    .loan-table {
        width: 100%;
        border-collapse: collapse;
    }
    .loan-table th, .loan-table td {
        padding: 16px 20px;
        text-align: left;
        border-bottom: 1px solid #f3f4f6;
    }
    .loan-table th {
        background: #f8fafc;
        font-weight: 600;
        font-size: 12px;
        text-transform: uppercase;
        color: var(--text-muted);
        letter-spacing: 0.5px;
    }
    .loan-table tr:hover td {
        background-color: #fafbfd;
    }
    .badge-pending-count {
        background-color: var(--warning);
        color: #ffffff;
        font-weight: 700;
        padding: 4px 10px;
        border-radius: 12px;
        font-size: 12px;
    }

    .btn-export {
        background: #0f172a;
        color: #fff;
        border: none;
        padding: 10px 18px;
        border-radius: 8px;
        cursor: pointer;
        font-weight: 600;
        font-family: inherit;
        display: inline-flex;
        align-items: center;
        gap: 8px;
        text-decoration: none;
        font-size: 14px;
        transition: 0.2s;
    }
    .btn-export:hover { background: #1e293b; }

    .link { color: var(--primary); text-decoration: none; font-weight: 500; transition: 0.2s; }
    .link:hover { color: var(--primary-dark); text-decoration: underline; }

    @media (max-width: 768px) {
        .sidebar { position: fixed; height: 100%; width: 0; padding: 0; overflow: hidden; }
        .sidebar.active { width: var(--sidebar-width); padding: 20px; }
    }
</style>
</head>
<body>
    <aside class="sidebar" id="sidebar">
        <div class="brand">
            <img src="../assets/images/logo.jpg" alt="Logo" onerror="this.src='https://via.placeholder.com/40'">
            <h2>AgroLoan Agent</h2>
        </div>

        <nav class="nav">
            <a href="agent_dashboard.php" class="nav-link">
                <i data-feather="home"></i>
                <span>Dashboard</span>
            </a>
            <a href="farmer_vetting.php" class="nav-link">
                <i data-feather="users"></i>
                <span>Farmer Vetting</span>
            </a>
            <a href="proof_verification.php" class="nav-link active">
                <i data-feather="check-square"></i>
                <span>Proof Verify</span>
            </a>
            <a href="agent_repayments.php" class="nav-link">
                <i data-feather="credit-card"></i>
                <span>Repayments</span>
            </a>
            <a href="dispute_center.php" class="nav-link">
                <i data-feather="alert-triangle"></i>
                <span>Dispute Center</span>
            </a>
            <a href="agent_profile.php" class="nav-link">
                <i data-feather="user"></i>
                <span>My Profile</span>
            </a>
        </nav>

        <form action="logout.php" method="POST">
            <button class="logout-btn">
                <i data-feather="log-out"></i>
                <span>Logout</span>
            </button>
        </form>
    </aside>

    <main class="main">
        <header class="topbar">
            <button id="toggleBtn" class="toggle-btn">
                <i data-feather="menu"></i>
            </button>
            
            <div class="user-profile">
                <div style="text-align:right; margin-right:8px;">
                    <div style="font-size:14px; font-weight:600;"><?= htmlspecialchars($username) ?></div>
                    <div style="font-size:12px; color:var(--text-muted);">Agent</div>
                </div>
                <div class="user-avatar">
                    <?= strtoupper(substr($username, 0, 1)) ?>
                </div>
            </div>
        </header>

        <div class="content-container">
            
            <!-- Dynamic header depending on drill-down status -->
            <?php if ($selected_app): ?>
                <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 15px; margin-bottom: 20px;">
                    <div>
                        <h1 style="margin: 0; font-size: 24px;">Verify Proofs: <?= htmlspecialchars($selected_app['title']) ?></h1>
                        <p style="color: var(--text-muted); margin: 5px 0 0 0;">
                            Farmer: <strong><?= htmlspecialchars($selected_app['farmer_name']) ?></strong> | Application ID: #<?= $selected_app['id'] ?>
                        </p>
                    </div>
                    
                    <div style="display: flex; align-items: center; gap: 15px;">
                        <a href="proof_verification.php?app_id=<?= $selected_app['id'] ?>&export=pdf" target="_blank" class="btn-export">
                            <i data-feather="printer"></i> Export PDF
                        </a>
                        <a href="proof_verification.php" class="link" style="display: flex; align-items: center; gap: 5px;">
                            <i data-feather="arrow-left" style="width:16px;"></i> Back to Loans List
                        </a>
                    </div>
                </div>
            <?php else: ?>
                <h1 style="margin-top:0;">Affiliated Loan Applications</h1>
                <p style="color:var(--text-muted);">View all loan accounts associated with your portfolio. Applications containing pending uploads are shown first.</p>
            <?php endif; ?>

            <hr style="border:0; border-top:1px solid #e5e7eb; margin: 20px 0;">

            <!-- DRILL-DOWN VIEW (Single Loan Proof Detail) -->
            <?php if ($selected_app): ?>
                
                <div class="proof-card">
                    <?php
                    $s_sql = "
                        SELECT ls.* 
                        FROM loan_stages ls 
                        WHERE ls.application_id = ?
                        ORDER BY ls.stage_number ASC
                    ";
                    $st = $pdo->prepare($s_sql);
                    $st->execute([$selected_app['id']]);
                    $stages = $st->fetchAll(PDO::FETCH_ASSOC);
                    ?>

                    <?php if (empty($stages)): ?>
                        <p style="color: var(--text-muted); text-align: center; padding: 20px;">No stages initialized for this loan application.</p>
                    <?php endif; ?>

                    <?php foreach ($stages as $stage): ?>
                        <div class="stage-row">
                            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
                                <div style="font-weight: 600; font-size: 15px; color: var(--primary);">
                                    Stage <?= htmlspecialchars($stage['stage_number']) ?> — GHS <?= number_format($stage['required_amount'], 2) ?>
                                </div>
                                <div>
                                    <span style="font-size: 12px; font-weight: 600; text-transform: uppercase; color: var(--text-muted);">
                                        Stage Status: <strong style="color: var(--text-main);"><?= strtoupper(htmlspecialchars($stage['status'])) ?></strong>
                                    </span>
                                </div>
                            </div>

                            <?php
                            $p_stmt = $pdo->prepare("
                                SELECT * FROM stage_proofs 
                                WHERE stage_id = ? 
                                ORDER BY (status = 'Pending') DESC, id DESC
                            ");
                            $p_stmt->execute([$stage['id']]);
                            $proofs = $p_stmt->fetchAll(PDO::FETCH_ASSOC);
                            ?>

                            <?php if (empty($proofs)): ?>
                                <p style="font-size: 12px; color: var(--text-muted); margin: 0; font-style: italic;">No uploads present for this stage yet.</p>
                            <?php else: ?>
                                <div class="proof-grid">
                                    <?php foreach ($proofs as $proof): ?>
                                        <?php 
                                        $p_filename = !empty($proof['filename']) ? $proof['filename'] : (!empty($proof['file_path']) ? $proof['file_path'] : '');
                                        $encodedFilename = rawurlencode($p_filename);
                                        $filePath = "../uploads/app_{$selected_app['id']}/stage_{$stage['id']}/{$encodedFilename}"; 
                                        $isImage = str_starts_with($proof['file_type'] ?? '', 'image');
                                        
                                        $isPending = (strtolower($proof['status']) === 'pending');
                                        $cardClass = $isPending ? 'pending' : 'processed';
                                        $p_type = $proof['proof_type'] ?? 'after';
                                        ?>

                                        <div class="proof-item <?= $cardClass ?>">
                                            <div>
                                                <!-- Phase Badge -->
                                                <?php if ($p_type === 'before'): ?>
                                                    <span class="phase-badge phase-before">Phase 1: Before Work</span>
                                                <?php elseif ($p_type === 'after'): ?>
                                                    <span class="phase-badge phase-after">Phase 2: After Work</span>
                                                <?php else: ?>
                                                    <span class="phase-badge phase-payment">Phase 3: Payment Proof</span>
                                                <?php endif; ?>

                                                <!-- File Preview -->
                                                <div class="proof-preview">
                                                    <a href="<?= htmlspecialchars($filePath) ?>" target="_blank">
                                                        <i data-feather="<?= $isImage ? 'image' : 'file-text' ?>" style="width:16px;"></i>
                                                        View <?= $isImage ? 'Image' : 'File' ?>
                                                    </a>
                                                </div>
                                            </div>

                                            <div>
                                                <div style="font-size:12px; color:#6b7280; margin-bottom:10px;">
                                                    Uploaded: <?= date('M d, Y H:i', strtotime($proof['created_at'] ?? $proof['uploaded_at'] ?? 'now')) ?>
                                                </div>

                                                <?php if ($isPending): ?>
                                                    <form method="POST">
                                                        <input type="hidden" name="proof_id" value="<?= $proof['id'] ?>">
                                                        <div class="proof-actions">
                                                            <button type="submit" name="action" value="approve" class="action-btn btn-verify">
                                                                Verify
                                                            </button>
                                                            <button type="submit" name="action" value="reject" class="action-btn btn-reject">
                                                                Reject
                                                            </button>
                                                        </div>
                                                    </form>
                                                <?php else: ?>
                                                    <div class="proof-actions">
                                                        <?php if (strtolower($proof['status']) === 'approved'): ?>
                                                            <span class="proof-badge badge-verified">
                                                                <i data-feather="check" style="width:12px; height:12px;"></i> Verified & Approved
                                                            </span>
                                                        <?php else: ?>
                                                            <span class="proof-badge badge-rejected">
                                                                <i data-feather="x" style="width:12px; height:12px;"></i> Rejected
                                                            </span>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>

                    <?php
                    // Display Farmer's historical verification items
                    $h_sql = "
                        SELECT sp.*, ls.stage_number, ls.id as stage_id, la.title as loan_title, la.id as app_id
                        FROM stage_proofs sp
                        JOIN loan_stages ls ON sp.stage_id = ls.id
                        JOIN loan_applications la ON ls.application_id = la.id
                        WHERE la.farmer_id = ? 
                        AND la.id != ? 
                        AND sp.status != 'Pending' 
                        ORDER BY la.id DESC, ls.stage_number DESC
                    ";
                    $hst = $pdo->prepare($h_sql);
                    $hst->execute([$selected_app['farmer_user_id'], $selected_app['id']]);
                    $historyProofs = $hst->fetchAll(PDO::FETCH_ASSOC);
                    ?>

                    <?php if(!empty($historyProofs)): ?>
                    <div class="history-section">
                        <details>
                            <summary>
                                <span>
                                    <i data-feather="archive" style="width:18px; height:18px; vertical-align:middle; margin-right:5px;"></i>
                                    View Proofs from Previous Loans
                                </span>
                            </summary>
                            <table class="history-table">
                                <thead>
                                    <tr>
                                        <th>Loan Application</th>
                                        <th>Stage</th>
                                        <th>File</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($historyProofs as $hp): ?>
                                        <?php
                                            $hpFilename = !empty($hp['filename']) ? $hp['filename'] : (!empty($hp['file_path']) ? $hp['file_path'] : '');
                                            $hpEncodedName = rawurlencode($hpFilename);
                                            $hpPath = "../uploads/app_{$hp['app_id']}/stage_{$hp['stage_id']}/{$hpEncodedName}";
                                            $statusClass = (strtolower($hp['status']) === 'approved') ? 'st-verified' : 'st-rejected';
                                        ?>
                                        <tr>
                                            <td><?= htmlspecialchars($hp['loan_title']) ?> (#<?= $hp['app_id'] ?>)</td>
                                            <td>Stage <?= htmlspecialchars($hp['stage_number']) ?></td>
                                            <td><a href="<?= htmlspecialchars($hpPath) ?>" target="_blank">View File</a></td>
                                            <td><span class="status-badge <?= $statusClass ?>"><?= htmlspecialchars($hp['status']) ?></span></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </details>
                    </div>
                    <?php endif; ?>

                </div>

            <!-- SUMMARY LIST VIEW (All Affiliated Loans) -->
            <?php else: ?>
                
                <div class="loan-table-card">
                    <?php if (empty($all_applications)): ?>
                        <div style="text-align:center; padding: 40px; color: var(--text-muted);">
                            <i data-feather="users" style="width:40px; height:40px; margin-bottom:10px;"></i>
                            <p>No affiliated loans found under your profile.</p>
                        </div>
                    <?php else: ?>
                        <table class="loan-table">
                            <thead>
                                <tr>
                                    <th>Loan ID</th>
                                    <th>Title</th>
                                    <th>Farmer</th>
                                    <th>Current Active Stage</th>
                                    <th>Disbursed/Total</th>
                                    <th>Pending Proofs</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($all_applications as $app_item): ?>
                                    <tr>
                                        <td>#<?= $app_item['id'] ?></td>
                                        <td style="font-weight: 600; color: var(--text-main);"><?= htmlspecialchars($app_item['title']) ?></td>
                                        <td><?= htmlspecialchars($app_item['farmer_name']) ?></td>
                                        <td>Stage <?= htmlspecialchars($app_item['current_stage']) ?></td>
                                        <td>
                                            <strong>GHS <?= number_format($app_item['disbursed_amount'], 2) ?></strong> 
                                            / GHS <?= number_format($app_item['amount'], 2) ?>
                                        </td>
                                        <td>
                                            <?php if ($app_item['pending_count'] > 0): ?>
                                                <span class="badge-pending-count"><?= $app_item['pending_count'] ?> action required</span>
                                            <?php else: ?>
                                                <span style="color: var(--success); font-size: 13px; font-weight: 500;">
                                                    <i data-feather="check" style="width:14px; height:14px; vertical-align:middle;"></i> Up to date
                                                </span>
                                            <?php endif; ?>
                                        </td>
                                        <td>
                                            <a href="proof_verification.php?app_id=<?= $app_item['id'] ?>" class="link" style="font-size: 13px; font-weight: 600;">
                                                View Proofs &rarr;
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    <?php endif; ?>
                </div>

            <?php endif; ?>

        </div>
    </main>

    <script>
        feather.replace();

        const toggleBtn = document.getElementById("toggleBtn");
        const sidebar = document.getElementById("sidebar");

        toggleBtn.addEventListener("click", () => {
            if (window.innerWidth <= 768) {
                sidebar.classList.toggle("active");
            } else {
                sidebar.classList.toggle("collapsed");
            }
        });

        <?php if (!empty($successMessage)): ?>
            Swal.fire({
                icon: 'success',
                title: 'Success',
                text: '<?= addslashes($successMessage) ?>',
                showConfirmButton: true,
                confirmButtonColor: '#1e40af'
            });
        <?php elseif (!empty($errorMessage)): ?>
            Swal.fire({
                icon: 'error',
                title: 'Error',
                text: '<?= addslashes($errorMessage) ?>',
                confirmButtonColor: '#ef4444'
            });
        <?php endif; ?>
    </script>
</body>
</html>